{{- if and .Values.dispatch.daemonset.enabled .Values.dispatch.daemonset.priorityClassCreate -}}
apiVersion: scheduling.k8s.io/v1
description: Used for udpfw dispatch Components to be scheduled with higher priority.
kind: PriorityClass
metadata:
  name: {{ .Values.dispatch.daemonset.priorityClassName | default (include "udpfw.fullname" . ) }}
preemptionPolicy: {{ .Values.dispatch.daemonset.priorityPreemptionPolicyValue }}
value: {{ .Values.dispatch.daemonset.priorityClassValue }}
{{- end }}
