{{- if .Values.dispatch.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "udpfw.dispatch.serviceAccountName" . }}
  labels:
    {{- include "udpfw.labels" . | nindent 4 }}
  {{- with .Values.dispatch.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
