apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "udpfw.nodelet-sidecar.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.nodelet.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "udpfw.nodelet-sidecar.labels" . | nindent 4 }}
    {{- with .Values.nodelet.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.nodelet.deployment.autoscaling.enabled }}
  replicas: {{ .Values.nodelet.deployment.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.nodelet.revisionHistoryLimit }}
  strategy: {{- toYaml .Values.nodelet.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "udpfw.nodelet-sidecar.selectorLabels" . | nindent 6 }}
      {{- with .Values.nodelet.pod.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "udpfw.nodelet-sidecar.selectorLabels" . | nindent 8 }}
        {{- with .Values.nodelet.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodelet.pod.annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.nodelet.pod.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodelet.pod.useHostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.nodelet.pod.dnsPolicy }}
      dnsPolicy: {{ . | quote }}
      {{- end }}
      containers:
        - name: nodelet
          image: "{{ .Values.nodelet.image.repository }}:{{ .Values.nodelet.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nodelet.image.pullPolicy }}
          {{- with .Values.nodelet.container.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /opt/udpfw/nodelet
          {{- with .Values.nodelet.container.lifecycle }}
          lifecycle: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodelet.container.ports }}
          ports:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodelet.container.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodelet.container.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodelet.container.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodelet.container.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.nodelet.container.env }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
            {{- if .Values.nodelet.container.envDict }}
            {{- range $key, $value := .Values.nodelet.container.envDict }}
            - name: {{ quote $key }}
              value: {{ quote $value }}
            {{- end }}
            {{- end }}
            - name: UDPFW_NODELET_IFACE
              value: {{ .Values.nodelet.container.iface | quote }}
            {{- if .Values.nodelet.container.dispatchAddress }}
            - name: UDPFW_DISPATCH_ADDRESS
              value: {{ .Values.nodelet.container.dispatchAddress | quote }}
            {{- end }}
            {{- if .Values.nodelet.container.namespace }}
            - name: UDPFW_NODELET_NAMESPACE
              value: {{ .Values.nodelet.container.namespace | quote }}
            {{- end }}
            {{- if .Values.nodelet.container.enableDebugLog }}
            - name: UDPFW_NODELET_DEBUG
              value: "true"
            {{- end }}
        {{ with .Values.nodelet.additionalContainers }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodelet.pod.tolerations }}
      tolerations: {{ toYaml .| nindent 8 }}
      {{- end }}
      {{- with .Values.nodelet.pod.affinity }}
      affinity: {{ toYaml .| nindent 8 }}
      {{- end }}
      {{- with .Values.nodelet.pod.nodeSelector }}
      nodeSelector: {{ toYaml .| nindent 8 }}
      {{- end }}
      {{- with .Values.nodelet.pod.topologySpreadConstraints }}
      topologySpreadConstraints: {{ toYaml .| nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "udpfw.nodelet-sidecar.serviceAccountName" . }}
