{{- if .Values.nodelet.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "udpfw.nodelet-sidecar.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.nodelet.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "udpfw.nodelet-sidecar.labels" . | nindent 4 }}
    {{- with .Values.nodelet.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.nodelet.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.nodelet.service.type }}
  {{- if .Values.nodelet.service.clusterIP }}
  clusterIP: {{ .Values.nodelet.service.clusterIP }}
  {{- end }}
  ports:
    {{- with .Values.nodelet.service.ports }}
      {{- toYaml . | nindent 4}}
    {{- end }}
  selector: {{- include "udpfw.nodelet-sidecar.selectorLabels" . | nindent 4 }}
{{- end }}
