apiVersion: v2
name: udpfw
description: A Helm chart for udpfw
type: application
version: 0.0.4
appVersion: "v0.1-alpha4"
sources:
  - https://github.com/udpfw/udpfw
maintainers:
  - name: Vito Sartori
    email: hey@vito.io
  - name: Thales Costa
    email: thalescostaa@gmail.com
dependencies:
  - name: nats
    version: 1.1.2
    repository: https://nats-io.github.io/k8s/helm/charts
    condition: nats.enabled
  - name: redis
    version: 18.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
